services:
  postgresql:
    image: 'postgres:16.1-alpine'
    env_file:
      - .env
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_ROOT_PASSWORD=oc2025-projet3!'
    ports:
      - '5432'
    volumes:
      - oc-projet3-db_data:/var/lib/postgresql/data
volumes:
  oc-projet3-db_data: