spring:
  application:
    name: datashare-backend
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://127.0.0.1:4200}

jwt:
  secret: ${JWT_SECRET:bGliZXJ0eVN0dWRlbnRCaWJsaW90aGVxdWVTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb24=}
  expiration-ms: ${JWT_EXPIRATION:86400000} # 24 heures en millisecondes

app:
  storage:
    path: ${STORAGE_PATH:/var/datashare/storage}
  file:
    max-size: ${MAX_FILE_SIZE:1073741824}
  download:
    base-url: ${DOWNLOAD_BASE_URL:http://localhost:4200/download}

logging:
  level:
    org:
      hibernate:
        type: info
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: info
    com:
      openclassrooms:
        datashare: info

management:
  endpoints:
    web:
      exposure:
        include: '*'